
spring:
  jpa:
    properties:
      hibernate:
        format_sql: 'TRUE'
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${PASSWORD}
    username: ${USERNAME}
    url: jdbc:mysql://localhost:3306/zoo_architect?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN
server:
  port: 8080

habitats:
  api:
    base-url: http://localhost:8081

jwt:
  secret: ${JWT_KEY:$2a$12$rJjJdUgI1NT7EQorqQfmR.EtLq7SDOM2cutE0Z5/9SX9tttd5il2W$2a$12$rJjJdUgI1NT7EQorqQfmR.EtLq7SDOM2cutE0Z5/9SX9tttd5il2W}
  expiration: ${JWT_EXPIRATION:60000}

